//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WjbuGangVer2_WebNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public string ChiTiet { get; set; }
        public int MaHD { get; set; }
        public int MaMH { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
