//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WjbuGangVer2_WebNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CmtID { get; set; }
        public int MaMH { get; set; }
        public int AccountID { get; set; }
        public string CmtMsg { get; set; }
        public Nullable<System.DateTime> CmtDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public string HoTen { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
